-- ============================================
-- CUSTOMER SHOPPING BEHAVIOR ANALYSIS
-- Database: projectDA
-- Table: customer
-- ============================================


-- ============================================
-- 1. DATABASE SETUP
-- ============================================

CREATE DATABASE projectDA;

USE projectDA;


-- ============================================
-- 2. BASIC DATA CHECK
-- ============================================

SELECT *
FROM customer
LIMIT 10;


-- ============================================
-- 3. REVENUE ANALYSIS
-- ============================================

-- Total revenue generated by male vs female customers

SELECT
    gender,
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;


-- Revenue contribution by age group

SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY CASE age_group
    WHEN 'Young' THEN 1
    WHEN 'Adult' THEN 2
    WHEN 'Middle_Aged' THEN 3
    WHEN 'Senior' THEN 4
END;


-- ============================================
-- 4. CUSTOMER SPENDING ANALYSIS
-- ============================================

-- Customers who used a discount but spent more
-- than the average purchase amount

SELECT
    customer_id
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
      SELECT AVG(purchase_amount)
      FROM customer
  );


-- Compare average spending between Express
-- and Standard shipping

SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;


-- ============================================
-- 5. SUBSCRIPTION ANALYSIS
-- ============================================

-- Compare subscribers and non-subscribers

SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;


-- Repeat buyers and subscription status

SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- ============================================
-- 6. PRODUCT ANALYSIS
-- ============================================

-- Top 5 products with the highest average review rating

SELECT
    item_purchased,
    ROUND(AVG(review_rating), 2) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;


-- Top 5 products with the highest percentage
-- of purchases where discount was applied

SELECT
    item_purchased,
    ROUND(
        SUM(CASE
            WHEN discount_applied = 'Yes' THEN 1
            ELSE 0
        END) * 100.0 / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


-- ============================================
-- 7. PRODUCT RANKING BY CATEGORY
-- ============================================

-- Top 3 most purchased products within each category

WITH product_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS purchase_count
    FROM customer
    GROUP BY category, item_purchased
),

ranked_products AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY purchase_count DESC
        ) AS rn
    FROM product_counts
)

SELECT
    category,
    item_purchased,
    purchase_count
FROM ranked_products
WHERE rn <= 3
ORDER BY category, rn;


-- ============================================
-- 8. CUSTOMER SEGMENTATION
-- ============================================

-- Segment customers based on previous purchases

WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;
